export type DemographicStory = {
  id: string;
  label: string;
  category: string;
  headline: string;
  body: string;
  primary: string;
  secondary: string;
  metricLabel: string;
  metricValue: string;
  metricDetail: string;
  panelTitle: string;
  panelItems: string[];
  tone: string;
  density: string;
  motion: string;
};

const stories: Record<string, DemographicStory> = {
  health: {
    id: 'health',
    label: 'Health',
    category: 'Wellness',
    headline: 'Training plans that feel safe to trust',
    body: 'Calm contrast, measured type, reassuring CTA language, and motion that never distracts from the next workout.',
    primary: 'Start today',
    secondary: 'View plan',
    metricLabel: 'Readiness',
    metricValue: '82%',
    metricDetail: '+8% from last week',
    panelTitle: 'Today',
    panelItems: ['Easy 5K base run', '10 min mobility', 'Hydration reminder'],
    tone: 'Calm',
    density: 'Cozy',
    motion: 'Short and grounded',
  },
  mental_wellness: {
    id: 'mental_wellness',
    label: 'Mental Wellness',
    category: 'Care',
    headline: 'A softer rhythm for reflective moments',
    body: 'Gentle hierarchy, reduced urgency, rounded touch targets, and copy that avoids pressure while still guiding action.',
    primary: 'Begin session',
    secondary: 'Save for later',
    metricLabel: 'Breathing pace',
    metricValue: '4-7-8',
    metricDetail: 'Guided for 3 minutes',
    panelTitle: 'Evening reset',
    panelItems: ['Low stimulus palette', 'Large pauses', 'Affirming microcopy'],
    tone: 'Quiet',
    density: 'Comfy',
    motion: 'Fade only',
  },
  productivity: {
    id: 'productivity',
    label: 'Productivity',
    category: 'Work',
    headline: 'Dense command surfaces without visual noise',
    body: 'Compact spacing, crisp controls, restrained accents, and fast state feedback for repeated daily work.',
    primary: 'Run workflow',
    secondary: 'Review queue',
    metricLabel: 'Cycle time',
    metricValue: '14m',
    metricDetail: '3 blockers cleared',
    panelTitle: 'Next actions',
    panelItems: ['Approve sprint notes', 'Assign follow-up', 'Export status'],
    tone: 'Precise',
    density: 'Compact',
    motion: 'Low latency',
  },
  ai_apps: {
    id: 'ai_apps',
    label: 'AI Apps',
    category: 'Assistant',
    headline: 'Expressive AI UI that still feels under control',
    body: 'More luminous accents, conversational hierarchy, streaming affordances, and clear user agency around generation.',
    primary: 'Generate draft',
    secondary: 'Tune context',
    metricLabel: 'Context fit',
    metricValue: '94',
    metricDetail: '7 sources grounded',
    panelTitle: 'Agent plan',
    panelItems: ['Clarify intent', 'Select components', 'Explain fit'],
    tone: 'Expressive',
    density: 'Cozy',
    motion: 'Interruptible',
  },
  kids: {
    id: 'kids',
    label: 'Kids',
    category: 'Learning',
    headline: 'Playful guidance with strong readability',
    body: 'Larger type, warmer colors, forgiving controls, and motion caps that keep delight from becoming chaos.',
    primary: 'Start quest',
    secondary: 'Practice first',
    metricLabel: 'Stars',
    metricValue: '12',
    metricDetail: '2 new badges',
    panelTitle: 'Today mission',
    panelItems: ['Read the clue', 'Tap the right shape', 'Celebrate progress'],
    tone: 'Playful',
    density: 'Comfy',
    motion: 'Bouncy but capped',
  },
  classic: {
    id: 'classic',
    label: 'Classic',
    category: 'Editorial',
    headline: 'Authority, restraint, and durable typography',
    body: 'Serif-led hierarchy, slower emphasis, restrained CTAs, and premium editorial spacing for trust-heavy products.',
    primary: 'Request review',
    secondary: 'Read brief',
    metricLabel: 'Review status',
    metricValue: '4/5',
    metricDetail: 'Counsel notes ready',
    panelTitle: 'Case summary',
    panelItems: ['Material risk', 'Decision window', 'Source appendix'],
    tone: 'Measured',
    density: 'Cozy',
    motion: 'Minimal',
  },
  gov: {
    id: 'gov',
    label: 'Government',
    category: 'Public Service',
    headline: 'Clear civic interfaces for high-stakes tasks',
    body: 'Plain language, robust contrast, predictable forms, and hierarchy that prioritizes completion over decoration.',
    primary: 'Check eligibility',
    secondary: 'Download guide',
    metricLabel: 'Application',
    metricValue: '3 steps',
    metricDetail: 'No account required',
    panelTitle: 'Required',
    panelItems: ['Identity check', 'Household details', 'Submit securely'],
    tone: 'Direct',
    density: 'Cozy',
    motion: 'Functional',
  },
  fintech: {
    id: 'fintech',
    label: 'Fintech',
    category: 'Finance',
    headline: 'Premium clarity for money decisions',
    body: 'Precise numbers, confident contrast, compact tables, and restrained trust signals for financial workflows.',
    primary: 'Review portfolio',
    secondary: 'Export report',
    metricLabel: 'Net flow',
    metricValue: '$42.8k',
    metricDetail: '+12.4% quarter to date',
    panelTitle: 'Allocation',
    panelItems: ['Treasury ladder', 'Index exposure', 'Cash buffer'],
    tone: 'Premium',
    density: 'Compact',
    motion: 'Subtle',
  },
  marketplace: {
    id: 'marketplace',
    label: 'Marketplace',
    category: 'Commerce',
    headline: 'Merchandising with conversion hierarchy',
    body: 'Warm product framing, clear price emphasis, social proof, and CTA contrast tuned for browsing and buying.',
    primary: 'Add to cart',
    secondary: 'Compare',
    metricLabel: 'Demand',
    metricValue: '1.8k',
    metricDetail: 'Saved this week',
    panelTitle: 'Featured pick',
    panelItems: ['Verified seller', 'Ships tomorrow', 'Easy returns'],
    tone: 'Inviting',
    density: 'Cozy',
    motion: 'Responsive',
  },
  teens: {
    id: 'teens',
    label: 'Teens',
    category: 'Youth',
    headline: 'Confident learning surfaces without childish cues',
    body: 'High contrast, expressive accents, social proof, and autonomy-first language for older students and youth communities.',
    primary: 'Join challenge',
    secondary: 'Preview path',
    metricLabel: 'Streak',
    metricValue: '9 days',
    metricDetail: '3 friends active',
    panelTitle: 'Next challenge',
    panelItems: ['Pick a track', 'Invite a teammate', 'Share progress'],
    tone: 'Energetic',
    density: 'Cozy',
    motion: 'Expressive but capped',
  },
  working_class: {
    id: 'working_class',
    label: 'Working Class',
    category: 'Practical',
    headline: 'Plainspoken tools that respect time and pressure',
    body: 'Direct copy, clear next steps, forgiving forms, and strong trust signals for practical high-friction tasks.',
    primary: 'Check options',
    secondary: 'Save and return',
    metricLabel: 'Time saved',
    metricValue: '18m',
    metricDetail: 'No phone call needed',
    panelTitle: 'Today',
    panelItems: ['Confirm details', 'Upload once', 'Get reminder'],
    tone: 'Useful',
    density: 'Cozy',
    motion: 'Fast and calm',
  },
  education: {
    id: 'education',
    label: 'Education',
    category: 'Learning',
    headline: 'Readable interfaces for students and teachers',
    body: 'Accessible type, clear scaffolding, progress states, and lower cognitive load across lessons and admin tasks.',
    primary: 'Start lesson',
    secondary: 'View rubric',
    metricLabel: 'Progress',
    metricValue: '7/10',
    metricDetail: '3 exercises left',
    panelTitle: 'Lesson flow',
    panelItems: ['Warm-up', 'Practice', 'Reflection'],
    tone: 'Supportive',
    density: 'Comfy',
    motion: 'Gentle',
  },
  religious: {
    id: 'religious',
    label: 'Religious',
    category: 'Community',
    headline: 'Reverent digital spaces with quiet guidance',
    body: 'Warm editorial rhythm, ceremonial restraint, and respectful CTAs for faith, community, and stewardship workflows.',
    primary: 'Join gathering',
    secondary: 'Read message',
    metricLabel: 'Community',
    metricValue: '124',
    metricDetail: 'Families updated',
    panelTitle: 'This week',
    panelItems: ['Service notes', 'Volunteer rota', 'Care requests'],
    tone: 'Reverent',
    density: 'Cozy',
    motion: 'Soft fade',
  },
  legal: {
    id: 'legal',
    label: 'Legal',
    category: 'Professional',
    headline: 'Formal review flows that feel precise and trustworthy',
    body: 'Serif hierarchy, restrained controls, defensible contrast, and document-first framing for legal work.',
    primary: 'Request counsel',
    secondary: 'Read brief',
    metricLabel: 'Review',
    metricValue: '4/5',
    metricDetail: 'One clause pending',
    panelTitle: 'Matter summary',
    panelItems: ['Risk notes', 'Decision window', 'Source appendix'],
    tone: 'Formal',
    density: 'Cozy',
    motion: 'Minimal',
  },
  erp: {
    id: 'erp',
    label: 'ERP',
    category: 'Operations',
    headline: 'Operational density with calm escalation',
    body: 'Compact data, predictable controls, quiet alerts, and tables designed for repeated back-office workflows.',
    primary: 'Approve batch',
    secondary: 'Open ledger',
    metricLabel: 'Queue',
    metricValue: '42',
    metricDetail: '6 need review',
    panelTitle: 'Controls',
    panelItems: ['Purchase orders', 'Inventory sync', 'Exception report'],
    tone: 'Operational',
    density: 'Compact',
    motion: 'Instant',
  },
  sales_crm: {
    id: 'sales_crm',
    label: 'Sales CRM',
    category: 'Revenue',
    headline: 'Pipeline surfaces that keep action obvious',
    body: 'Clear priority, tight cards, confident CTAs, and next-step language for sales teams moving quickly.',
    primary: 'Advance deal',
    secondary: 'Log note',
    metricLabel: 'Pipeline',
    metricValue: '$84k',
    metricDetail: '3 deals warming',
    panelTitle: 'Today focus',
    panelItems: ['Call prospect', 'Send proposal', 'Book renewal'],
    tone: 'Decisive',
    density: 'Compact',
    motion: 'Fast feedback',
  },
  hightech: {
    id: 'hightech',
    label: 'High Tech',
    category: 'Technical',
    headline: 'Technical products with an intelligent edge',
    body: 'Crisp layouts, luminous accents, dense context, and component choices that feel advanced without becoming noisy.',
    primary: 'Deploy model',
    secondary: 'Inspect logs',
    metricLabel: 'Latency',
    metricValue: '42ms',
    metricDetail: 'p95 stable',
    panelTitle: 'System',
    panelItems: ['Model health', 'Token budget', 'Edge status'],
    tone: 'Advanced',
    density: 'Compact',
    motion: 'Precise',
  },
  social: {
    id: 'social',
    label: 'Social',
    category: 'Community',
    headline: 'Expressive surfaces for participation and belonging',
    body: 'Warm color, softer cards, visible reactions, and momentum cues without turning everything into a notification.',
    primary: 'Post update',
    secondary: 'Browse feed',
    metricLabel: 'Reach',
    metricValue: '2.4k',
    metricDetail: '184 replies',
    panelTitle: 'Community pulse',
    panelItems: ['Trending thread', 'New mention', 'Creator prompt'],
    tone: 'Expressive',
    density: 'Cozy',
    motion: 'Responsive',
  },
  monitoring: {
    id: 'monitoring',
    label: 'Monitoring',
    category: 'Observability',
    headline: 'Incident surfaces with ruthless signal priority',
    body: 'Dense metrics, hard contrast, status-first hierarchy, and motion used only for state changes that matter.',
    primary: 'Acknowledge',
    secondary: 'Open runbook',
    metricLabel: 'Uptime',
    metricValue: '99.98%',
    metricDetail: '2 warnings active',
    panelTitle: 'Signals',
    panelItems: ['API latency', 'Queue depth', 'Region health'],
    tone: 'Alert',
    density: 'Compact',
    motion: 'State-only',
  },
  listings: {
    id: 'listings',
    label: 'Listings',
    category: 'Discovery',
    headline: 'Scannable inventory with trust cues up front',
    body: 'Dense comparison, verified metadata, strong filters, and CTAs that support browsing before commitment.',
    primary: 'View listing',
    secondary: 'Compare',
    metricLabel: 'Matches',
    metricValue: '38',
    metricDetail: '6 verified today',
    panelTitle: 'Highlights',
    panelItems: ['Verified owner', 'Nearby match', 'Saved search'],
    tone: 'Informative',
    density: 'Compact',
    motion: 'Responsive',
  },
  military: {
    id: 'military',
    label: 'Military',
    category: 'Command',
    headline: 'Mission-first interfaces with disciplined hierarchy',
    body: 'Low-ambiguity controls, strong status language, muted palette, and restrained motion for serious operational contexts.',
    primary: 'Confirm status',
    secondary: 'Open protocol',
    metricLabel: 'Readiness',
    metricValue: 'Green',
    metricDetail: '2 checks pending',
    panelTitle: 'Protocol',
    panelItems: ['Verify unit', 'Check equipment', 'Escalate exception'],
    tone: 'Disciplined',
    density: 'Compact',
    motion: 'Minimal',
  },
  special_occasion: {
    id: 'special_occasion',
    label: 'Special Occasion',
    category: 'Celebration',
    headline: 'Event pages with delight and clear conversion',
    body: 'Expressive color, festive CTA hierarchy, elegant pacing, and invitation flows that still stay readable.',
    primary: 'Reserve spot',
    secondary: 'View details',
    metricLabel: 'Guests',
    metricValue: '86',
    metricDetail: '14 seats left',
    panelTitle: 'Event plan',
    panelItems: ['RSVP list', 'Gift note', 'Schedule'],
    tone: 'Celebratory',
    density: 'Cozy',
    motion: 'Graceful',
  },
  classic_ancient: {
    id: 'classic_ancient',
    label: 'Ancient Classic',
    category: 'Parchment',
    headline: 'A scroll-like interface for heritage and ancient knowledge',
    body: 'Parchment warmth, serif authority, carved-border restraint, and slow ceremonial hierarchy for archives, mythic education, and historical products.',
    primary: 'Open scroll',
    secondary: 'Study archive',
    metricLabel: 'Codex',
    metricValue: 'VII',
    metricDetail: 'Three chapters restored',
    panelTitle: 'Inscription',
    panelItems: ['Primary source', 'Translator note', 'Lineage map'],
    tone: 'Ceremonial',
    density: 'Cozy',
    motion: 'Page-turn subtle',
  },
};

export function storyForDemographic(id: string): DemographicStory {
  return stories[id] ?? stories.productivity!;
}

export function allStories(ids: readonly string[]): DemographicStory[] {
  return ids.map((id) => storyForDemographic(id));
}
