import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: '{{APP_TITLE}}',
  description: 'Generated by Skeed.',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
